### PR TITLE
Styleing

### PR DESCRIPTION
**Pull request by PowerLevel9000**
# styling various pages and components;

## Form

due to my personal requirement I have to change little form styling as it was looking weird with style given;
- [ ] Form styled 
- [ ] button Components
- [ ] loader;
- [ ] category input ;
- [ ] random updates;

## happy coding

HappyHoliHoliGIF

## as we have festival week so I got late 😑😑😁

### CODE REVIEW

**Review by frank1738 — CHANGES_REQUESTED** [review]
Hi @PowerLevel9000 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!




## Highlights

✅ Correct use of Gitflow
✅ No linter error
✅ App is designed as expected 👍 


## Required Changes ♻️
- [ ] Kindly update the `live version` on your readme file to contain the deployed version of your project.

## Optional suggestions

N/A


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by AmaduKamara — APPROVED** [review]
# Status: Approved 🟢 🟢 🟢

Hi @PowerLevel9000,

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

## Highlights:

✅ You used Gitflow correctly 👍🏽
✅ Linter checks passed 👍🏽
✅ Your app is nicely styled 👍🏽
✅ Adding and removing book features work fine 👍🏽

## Suggestions:

- [ ] What if you could work on the categories page and center the button and the under construction text that shows when the button is clicked or better you have them be inside a container style so they won't be at the left corner? That will improve the whole look and feel of the app 👍🏽
- [ ] Also, it would be nice if the category input field be a select input so the user selects a category of a book from a list of categories you will add upfront.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by PowerLevel9000** [comment]
# Suggestion considered

hi @AmaduKamara  thanks for those suggestion i really appreciate you take some time to look deep in my design 
i will consider your suggests however i have some more things in my mind i will complete itin my free time 

## to be honest

 to be honest same and a little bit more I want to do that but as the deadline was approaching I just want to complete the requirement part

**Comment by AmaduKamara** [comment]
It's okay brother, I understand. 
Your work looks great. Take your time, maybe later you can work on more features in your free time. Focus on deadlines at the moment. 
You're doing great so far 👍

**Pull request merged**
